### ISSUE TITLE
能否发一下具体的接线教程

### ISSUE THREAD

**Issue by chinabestcountry** [chenziwenhaoshuai/WaterRemind#1]
能否发一下具体的接线教程
急需
谢谢了！
:)

**Comment by chenziwenhaoshuai** [comment]
> 

https://blog.csdn.net/dudu199806/article/details/122957200这里面有手绘的接线图

**Comment by chinabestcountry** [comment]
报错
错误提示如下：
WaterRemind:13:1: error: 'DS1302' does not name a type; did you mean 'CS12'?
 DS1302 rtc(2, 3, 4); // RST, DAT, CLK
 ^~~~~~
 CS12
WaterRemind:14:1: error: 'Time' does not name a type; did you mean 'Wire'?
 Time t1;
 ^~~~
 Wire
WaterRemind:15:1: error: 'Time' does not name a type; did you mean 'Wire'?
 Time t2;
 ^~~~
 Wire
F:\Users\pxyxm\Downloads\WaterRemind-main\waterremind\WaterRemind\WaterRemind.ino: In function 'void setup()':
WaterRemind:61:17: error: a function-definition is not allowed here before '{' token
 void loop(void) {
                 ^
WaterRemind:131:1: error: expected '}' at end of input
 }
 ^
exit status 1
'DS1302' does not name a type; did you mean 'CS12'?

**Comment by chenziwenhaoshuai** [comment]
> 报错 错误提示如下： WaterRemind:13:1: error: 'DS1302' does not name a type; did you mean 'CS12'? DS1302 rtc(2, 3, 4); // RST, DAT, CLK ^~~~~~ CS12 WaterRemind:14:1: error: 'Time' does not name a type; did you mean 'Wire'? Time t1; ^~~~ Wire WaterRemind:15:1: error: 'Time' does not name a type; did you mean 'Wire'? Time t2; ^~~~ Wire F:\Users\pxyxm\Downloads\WaterRemind-main\waterremind\WaterRemind\WaterRemind.ino: In function 'void setup()': WaterRemind:61:17: error: a function-definition is not allowed here before '{' token void loop(void) { ^ WaterRemind:131:1: error: expected '}' at end of input } ^ exit status 1 'DS1302' does not name a type; did you mean 'CS12

> 

注释掉就好
